"""Added the QuizSummary table

Revision ID: 53929d437ea8
Revises: 315304f80c99
Create Date: 2025-05-15 15:12:12.630524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53929d437ea8'
down_revision = '315304f80c99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('result_id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(length=120), nullable=False),
    sa.Column('correct_answers', sa.Integer(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('time_per_question', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ),
    sa.ForeignKeyConstraint(['result_id'], ['quiz_result.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('result_id')
    )
    with op.batch_alter_table('quiz_summary', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_summary_user_email'), ['user_email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_summary', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_summary_user_email'))

    op.drop_table('quiz_summary')
    # ### end Alembic commands ###
