"""added description

Revision ID: 69ab78d7e941
Revises: f051211085f6
Create Date: 2025-05-16 14:52:53.199328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69ab78d7e941'
down_revision = 'f051211085f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    with op.batch_alter_table('quiz_share', schema=None) as batch_op:
        batch_op.alter_column('shared_with_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('recipient_email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_share', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipient_email', sa.VARCHAR(length=120), nullable=True))
        batch_op.alter_column('shared_with_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
