"""Add QuizShare model

Revision ID: 71e852fbc84e
Revises: 113b6fa06ef7
Create Date: 2025-05-14 03:03:19.324095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71e852fbc84e'
down_revision = '113b6fa06ef7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_share', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shared_with_user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('shared_by_user_id', sa.Integer(), nullable=False))
        batch_op.alter_column('shared_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        # Drop constraints only if they exist
        existing_constraints = batch_op.get_bind().engine.dialect.get_foreign_keys(batch_op.get_bind(), 'quiz_share')
        for constraint in existing_constraints:
            if constraint['name'] in ['fk_quiz_share_shared_by_id', 'fk_quiz_share_shared_with_id']:
                batch_op.drop_constraint(constraint['name'], type_='foreignkey')
        batch_op.create_foreign_key('fk_quiz_share_shared_with_user', 'user', ['shared_with_user_id'], ['id'])
        batch_op.create_foreign_key('fk_quiz_share_shared_by_user', 'user', ['shared_by_user_id'], ['id'])
        batch_op.drop_column('shared_with_id')
        batch_op.drop_column('shared_by_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_share', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shared_by_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('shared_with_id', sa.INTEGER(), nullable=False))
        # Drop constraints only if they exist
        existing_constraints = batch_op.get_bind().engine.dialect.get_foreign_keys(batch_op.get_bind(), 'quiz_share')
        for constraint in existing_constraints:
            if constraint['name'] in ['fk_quiz_share_shared_with_user', 'fk_quiz_share_shared_by_user']:
                batch_op.drop_constraint(constraint['name'], type_='foreignkey')
        batch_op.create_foreign_key('fk_quiz_share_shared_with_id', 'user', ['shared_with_id'], ['id'])
        batch_op.create_foreign_key('fk_quiz_share_shared_by_id', 'user', ['shared_by_id'], ['id'])
        batch_op.alter_column('shared_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_column('shared_by_user_id')
        batch_op.drop_column('shared_with_user_id')

    # ### end Alembic commands ###
