"""Add quiz_duration to QuizResult

Revision ID: d723afd63774
Revises: ce3e2c0529df
Create Date: 2025-05-09 18:16:46.351424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd723afd63774'
down_revision = 'ce3e2c0529df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quiz_duration', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_result', schema=None) as batch_op:
        batch_op.drop_column('quiz_duration')

    # ### end Alembic commands ###
