"""Added recipient_email to QuizShare model and made shared_with_user_id nullable

Revision ID: f051211085f6
Revises: 4a8aecd983ef
Create Date: 2025-05-14 11:19:30.332627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f051211085f6'
down_revision = '4a8aecd983ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_quiz_share',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('recipient_email', sa.String(length=120), nullable=False),
    sa.Column('shared_by_user_id', sa.Integer(), nullable=False),
    sa.Column('shared_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ),
    sa.ForeignKeyConstraint(['shared_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=False))

    with op.batch_alter_table('quiz_share', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipient_email', sa.String(length=120), nullable=True))
        batch_op.alter_column('shared_with_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('picture')

    with op.batch_alter_table('quiz_share', schema=None) as batch_op:
        batch_op.alter_column('shared_with_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('recipient_email')

    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.drop_column('is_public')

    op.drop_table('pending_quiz_share')
    # ### end Alembic commands ###
